"""phase9_accessibility_content

Revision ID: 0f5657e829f5
Revises: 0008_phase8_performance
Create Date: 2026-08-17 13:53:34.543157
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0f5657e829f5'
down_revision: Union[str, Sequence[str], None] = '0008_phase8_performance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=2048), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_findings_category'), 'accessibility_findings', ['category'], unique=False)
    op.create_index(op.f('ix_accessibility_findings_classification'), 'accessibility_findings', ['classification'], unique=False)
    op.create_index(op.f('ix_accessibility_findings_page_id'), 'accessibility_findings', ['page_id'], unique=False)
    op.create_index(op.f('ix_accessibility_findings_scan_id'), 'accessibility_findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_accessibility_findings_subject'), 'accessibility_findings', ['subject'], unique=False)
    op.create_table('content_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=2048), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_findings_category'), 'content_findings', ['category'], unique=False)
    op.create_index(op.f('ix_content_findings_classification'), 'content_findings', ['classification'], unique=False)
    op.create_index(op.f('ix_content_findings_page_id'), 'content_findings', ['page_id'], unique=False)
    op.create_index(op.f('ix_content_findings_scan_id'), 'content_findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_content_findings_subject'), 'content_findings', ['subject'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_content_findings_subject'), table_name='content_findings')
    op.drop_index(op.f('ix_content_findings_scan_id'), table_name='content_findings')
    op.drop_index(op.f('ix_content_findings_page_id'), table_name='content_findings')
    op.drop_index(op.f('ix_content_findings_classification'), table_name='content_findings')
    op.drop_index(op.f('ix_content_findings_category'), table_name='content_findings')
    op.drop_table('content_findings')
    op.drop_index(op.f('ix_accessibility_findings_subject'), table_name='accessibility_findings')
    op.drop_index(op.f('ix_accessibility_findings_scan_id'), table_name='accessibility_findings')
    op.drop_index(op.f('ix_accessibility_findings_page_id'), table_name='accessibility_findings')
    op.drop_index(op.f('ix_accessibility_findings_classification'), table_name='accessibility_findings')
    op.drop_index(op.f('ix_accessibility_findings_category'), table_name='accessibility_findings')
    op.drop_table('accessibility_findings')
    # ### end Alembic commands ###
