"""Add AIInterpretation model

Revision ID: c4ad62bb8e7b
Revises: 0f5657e829f5
Create Date: 2026-08-17 15:50:11.943046
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'c4ad62bb8e7b'
down_revision: Union[str, Sequence[str], None] = '0f5657e829f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interpretations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=2048), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interpretations_category'), 'ai_interpretations', ['category'], unique=False)
    op.create_index(op.f('ix_ai_interpretations_classification'), 'ai_interpretations', ['classification'], unique=False)
    op.create_index(op.f('ix_ai_interpretations_scan_id'), 'ai_interpretations', ['scan_id'], unique=False)
    op.create_index(op.f('ix_ai_interpretations_subject'), 'ai_interpretations', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interpretations_subject'), table_name='ai_interpretations')
    op.drop_index(op.f('ix_ai_interpretations_scan_id'), table_name='ai_interpretations')
    op.drop_index(op.f('ix_ai_interpretations_classification'), table_name='ai_interpretations')
    op.drop_index(op.f('ix_ai_interpretations_category'), table_name='ai_interpretations')
    op.drop_table('ai_interpretations')
    # ### end Alembic commands ###
